### PR TITLE
Add primary key id to table incoming.

### PR DESCRIPTION
**Pull request by pinkra**
http://issues.freepbx.org/browse/FREEPBX-13745

### CODE REVIEW

**Comment by tm1000** [comment]
This only adds the key on new installs. Is that intended?

**Comment by pinkra** [comment]
If it's simple can we add also a migration for upgrades?

**Comment by tm1000** [comment]
I am asking if that is something you need or not.

**Comment by pinkra** [comment]
Yes, it is needed..

**Pull request merged**
