### PR TITLE
Make FreePBX\Database::query() compatible with PDO::query()

### PR DESCRIPTION
**Pull request by miken32**
Resolves a fatal error and allows for upgrades to 17 using PHP 8

### CODE REVIEW

**Comment by miken32** [comment]
(Tested with PHP 7.4, but should be fine with older as well)

**Comment by kapilgupta01** [comment]
Hi @miken32 thanks for your contribution,. may be this is better to fix for 17 instead of touching 16?

Regards
Kapil

**Comment by miken32** [comment]
@kguptasangoma it's already in 17, because it causes a fatal error in modern versions of PHP. The whole point is to add it to 16 so that it works enough to do the upgrade without dying.

**Comment by kapilgupta01** [comment]
Hi @miken32 How are you doing upgrade to 17 from 16 ? We have tried backup and restore and did not faced any issue? Are you trying to upgrade Debian OS running with 16 to update to 17 (just by module updates) ?

My worry is, this is main DB api and we are changing the definition to add the arguments and we may be calling this "query" api without arguments in many places in the Freepbx so we have to change all those places as well in 16.

17 we have modified the code in order to bring up the entire codebase to compatible with the latest PHP 8.2.

**Comment by miken32** [comment]
I can’t imagine why you would run a query function without a query, but this is a simple thing to check for in the codebase. If it is happening, I’m sure it’s not common or intentional. Or, I haven’t checked, but setting a default like `string $query = ''` may work as well to keep PHP happy. I can check that tomorrow. 

Backup and restore is a very poor plan for anyone who is running FreePBX in a professional capacity. We have over 75 PBXs to deal with. Not to mention my team has over 50 years combined experience with administering RHEL systems and an infrastructure designed for managing them, so I am not about to throw that away to change to Debian.

We plan to upgrade in place like every other upgrade since 2.0 days. Ideally we can get 16 patched to make that easier for us and others.

**Comment by miken32** [comment]
@kguptasangoma nowhere in the code is using `Database::query()` without arguments that I could see, but I have added a default value just in case it's being mis-called somewhere in a little-used module.

**Review by jissphilip — APPROVED** [review]

**Review by kapilgupta01 — APPROVED** [review]

**Pull request merged**
