### PR TITLE
Some debug on the old stable branch 12.0

### PR DESCRIPTION
**Pull request by javyer**
Hello,
We do need to use your old stable branch 12.0, and we have some found some bugs. Here are the patchs we use.

Best Regards

### CODE REVIEW

**Comment by tm1000** [comment]
This requires a CLA on file: http://wiki.freepbx.org/display/FOP/Code+License+Agreement

**Comment by tm1000** [comment]
No CLA received. Closing

**Comment by javyer** [comment]
Hello,

Please can you reopen, I'm on the way to sign this CLA, i was waitting 
the GO from my co-founder...
Or i need to create a new pull request ?

Thanks

**Comment by tm1000** [comment]
No problem :-)

**Comment by javyer** [comment]
Hello,

Here is the signed CLA

Best Regards

Javier Sixto

**Pull request merged**
