### PR TITLE
Fix incorrect language detection

### PR DESCRIPTION
**Pull request by miken32**
The more I looked, the messier it got. Not sure if $lang should be provided by something else but this seems to be in line with what other code is doing to determine language.

### CODE REVIEW

**Comment by miken32** [comment]
The more I looked, the messier it got. Not sure if $lang should be provided by something else but this seems to be in line with what other code is doing to determine language.

**Comment by tm1000** [comment]
No this is wrong. $lang is set higher up from a function that processes lang. That fact that your lang is empty means something is wrong with your system

**Comment by miken32** [comment]
Ok, that makes sense. How about `$l`?

Any ideas what could be causing an empty language? `$amp_conf["UIDEFAULTLANG"]` is set to en_US, cookies are enabled, on the system level, `LANG=en_CA.utf-8`.

Should $lang be coming from `set_language()` in `view.functions.php`? I put in a debugging line and it returns "en_US" every time it's called. The only time its return is assigned is in `config.php` but that's assigned to `$language`.

**Comment by tm1000** [comment]
you are right about "l" but for me "lang" is set correctly. Yes it comes from set_language()

**Comment by miken32** [comment]
Looks like it's set in `config.php` but not `ajax.php` so the popups don't get it. It's not just empty, it's undefined.

**Comment by tm1000** [comment]
I think you have found a bug but you are honestly confused about how the system works. The "popovers" do not go through ajax.php

**Comment by miken32** [comment]
Sorry, our production systems are still on 11. Yesterday was my first look at the new UI, but I don't have all the time I'd like to dig into it, so I'll cop to being confused! I spotted a request via ajax.php, looks like it was just something for search.

So, the popover does go through `config.php` but when `$fw_popover` is set, the code that sets `$footer["lang"]` isn't called. Quick fix would be to set `$footer["lang"] inside the `$fw_popover` block.

Cleaner fix would be to set up default settings in `$footer` before the conditional, change specific values inside the conditional, and only have one call to `load_gui()`.

**Pull request closed without merging**
